manifest_version = "0.1.0"

[project]
id = "icp-nft-vault"
name = "Mintlab"

[workspace]
include = [
  "src/backend/caffeine.toml",
  "src/backend/mops.toml",
  "src/backend/mops.lock",
  "src/backend/main.mo",
  "src/backend/main.did",
  "src/backend/collection_canister/**",
  "src/backend/lib/**",
  "src/backend/mixins/**",
  "src/backend/system-idl/**",
  "src/backend/types/**",
  "src/frontend/caffeine.toml",
  "src/frontend/package.json",
  "src/frontend/index.html",
  "src/frontend/env.json",
  "src/frontend/tsconfig.json",
  "src/frontend/vite.config.js",
  "src/frontend/postcss.config.js",
  "src/frontend/tailwind.config.js",
  "src/frontend/biome.json",
  "src/frontend/components.json",
  "src/frontend/public/**",
  "src/frontend/src/**",
  "scripts/**",
  "caffeine.json",
  "package.json",
  "pnpm-lock.yaml",
  "pnpm-workspace.yaml",
  "tsconfig.json",
  "mops.toml",
  "mops.lock",
  "project.json",
]

[canisters.frontend]
depends_on = ["backend"]
